name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config --local user.email "gameliker16@naver.com"
        git config --local user.name "kjm4027"

    - name: Create empty commit
      run: |
        git commit --allow-empty -m "Daily commit $(date)" 

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
